# Generated by Django 3.1.4 on 2021-02-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadbodydetection',
            name='image',
            field=models.ImageField(upload_to='bodyPartsDetection_result_dump'),
        ),
    ]
